### ISSUE TITLE
Skill doesn't get registered when app is started

### ISSUE THREAD

**Issue by axelclark** [col/alexa#4]
This is a great project, thanks for your work on in it!

I'm trying to follow the ReadMe, but the skill is not getting registered.  I created a new mix project.  Updated the mix.exs file.  Then created a module with the sample skill.

https://github.com/axelclark/alexa_hello_world/blob/master/lib/alexa_hello_world.ex

```elixir
defmodule AlexaHelloWorld do
  @moduledoc """
  Documentation for AlexaHelloWorld.
  """

  use Alexa.Skill, ap_id: "123"

  def handle_intent("SayHello", request, response) do
    response |> say("Hello World!")
  end
end
```

When I start start the app using ```iex -S mix```, I have to call register_skill to add it to the registry:

```bash
08:35:20.089 [debug] Starting Alexa.Registry
Interactive Elixir (1.4.0) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> Alexa.Registry.get_skill("123")           
Alexa.UnknownSkill
iex(2)> Alexa.Registry.register_skill("123", AlexaHelloWorld)                   
:ok              
iex(3)> Alexa.Registry.get_skill("123")                      
AlexaHelloWorld
```

I must be missing a step in the set up.  Is there something else I need to do?  Thanks!

**Comment by col** [comment]
Looks like the README needs to be updated.

You need to start a worker process for your skill. Add something like this to your applications supervision tree.

    worker(AlexaHelloWorld, [])

You can also optionally pass the app_id at this point as well.

    worker(AlexaHelloWorld, [[app_id: Application.get_env(:alexa_hello_word, :alexa_app_id)]])

Hope that help.

I'll update the README later. You're always welcome to submit a pull request.

**Comment by axelclark** [comment]
Ok, thanks!!

**Comment by axelclark** [comment]
I'll send a pull request for the README update.
